import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, BarChart3, CheckCheck, Sparkles, Workflow } from "lucide-react";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/solutions/$slug")({
  component: SolutionPage,
});

const solutionData: Record<string, { title: string; category: string; summary: string; outcomes: string[] }> = {
  "gohighlevel-expert": { title: "GoHighLevel Expert", category: "GoHighLevel Systems", summary: "CRM architecture, pipeline logic, calendars, funnels and workflows configured around how your business actually sells.", outcomes: ["Client-owned account architecture", "Pipeline, fields and calendar design", "Automation built around real edge cases"] },
  "gohighlevel-setup": { title: "GoHighLevel Setup", category: "GoHighLevel Systems", summary: "A clean, compliant GoHighLevel foundation that gives your team one reliable operating picture from day one.", outcomes: ["Sub-account and domain setup", "Email and SMS deliverability", "Team permissions and handover"] },
  "gohighlevel-crm-setup": { title: "GoHighLevel CRM Setup", category: "GoHighLevel Systems", summary: "Every lead, stage, source and appointment organized into a CRM your team can actually use.", outcomes: ["Custom opportunity stages", "Source and campaign attribution", "Routing, ownership and notifications"] },
  "gohighlevel-automation": { title: "GoHighLevel Automation", category: "GoHighLevel Systems", summary: "Multi-step follow-up and escalation that keeps working after hours, across weekends and through real-world edge cases.", outcomes: ["Lead response workflows", "Conditional nurture and escalation", "Stop-on-reply automation logic"] },
  "gohighlevel-funnels": { title: "GoHighLevel Funnels", category: "GoHighLevel Systems", summary: "High-converting landing, booking and qualification funnels connected directly to the CRM.", outcomes: ["Direct-response funnel architecture", "Qualification and booking paths", "Conversion tracking and testing"] },
  "gohighlevel-migration": { title: "GoHighLevel Migration", category: "GoHighLevel Systems", summary: "Move from disconnected tools or a broken account into a clean system without losing operational context.", outcomes: ["Data and pipeline migration", "Redirect and integration planning", "Testing before live cutover"] },
  "ai-voice-agents": { title: "AI Voice Agents That Hold a Real Conversation", category: "AI Voice", summary: "Not a phone tree with better audio. A voice agent that understands the caller, asks the right questions, writes structured data into your CRM and books or transfers before the call ends.", outcomes: ["Conversation design, branches and guardrails", "Vapi or Retell build with telephony and warm transfer", "CRM function calling, recording, transcription and QA"] },
  "ai-receptionist": { title: "An AI Receptionist That Answers Every Call, at Any Hour", category: "AI Voice", summary: "The call that reaches voicemail at 7pm is usually the call that reaches a competitor by morning. Answer inbound calls, identify intent, handle routine questions and book against live availability.", outcomes: ["First-ring inbound call handling", "Knowledge-based answers for hours, location and pricing", "Warm transfer, missed-call recovery and CRM logging"] },
  "ai-appointment-setter": { title: "An AI Appointment Setter That Works Your List Every Day", category: "AI Voice", summary: "Call every new lead within seconds, work dormant lists nobody has time for, handle common objections and book qualified appointments directly into the calendar.", outcomes: ["Instant speed-to-lead calling and retry cadence", "Conversational qualification and objection handling", "Confirmation, no-show reduction and connect-rate reporting"] },
  "ai-sdr": { title: "An AI SDR for the Prospecting Nobody Has Time To Do", category: "AI Voice", summary: "An outbound sales-development system that reaches prospects who have not enquired, establishes fit, handles initial objections and books qualified meetings into the pipeline.", outcomes: ["Precisely defined ICP and qualification criteria", "Multi-touch cadence with consent and suppression controls", "CRM logging and informed meeting handoff"] },
  "ai-calling-bots": { title: "AI Calling Bots", category: "AI Voice", summary: "A calling layer designed around your offer, your compliance requirements and your follow-up rules.", outcomes: ["Multi-step call sequences", "Recovery and retry logic", "Call outcomes written to CRM"] },
  "ai-chatbot": { title: "A Website Chatbot That Books, Not One That Deflects", category: "AI Chat & Messaging", summary: "Answer from your own content, qualify visitors, capture structured CRM fields and book appointments while the visitor is still engaged.", outcomes: ["Grounded knowledge base with explicit limits", "Qualification flow and live calendar booking", "Human handoff with full conversation context"] },
  "conversational-ai": { title: "One Agent, Consistent Across Every Channel", category: "AI Chat & Messaging", summary: "One knowledge base and one set of behavioral rules across web chat, messaging apps, SMS and voice, so customers receive consistent answers wherever they start.", outcomes: ["Shared knowledge base and channel-appropriate behavior", "Conversation context carried between channels", "Unified CRM logging and consistent escalation rules"] },
  "ai-customer-support": { title: "Deflect the Questions That Never Needed a Person", category: "AI Chat & Messaging", summary: "Handle documented, repetitive questions, order status, delivery, returns, billing and how-to requests, while escalating complaints, exceptions and uncertainty with context.", outcomes: ["Knowledge-grounded answers and live order lookups", "Escalation rules that preserve the full conversation", "Resolution-rate and documentation-gap reporting"] },
  "whatsapp-automation": { title: "WhatsApp Automation on the Channel People Actually Reply To", category: "AI Chat & Messaging", summary: "Build around Meta templates, the 24-hour reply window and quality ratings so WhatsApp becomes a reliable two-way channel instead of a personal-phone bottleneck.", outcomes: ["Business API setup, verification and template approval", "Two-way routing into GoHighLevel with AI-assisted replies", "In-chat booking, opt-out handling and quality-rating protection"] },
  "instagram-dm-automation": { title: "Instagram DM Automation", category: "AI Chat & Messaging", summary: "Turn Instagram conversations into qualified leads and booked calls without manual inbox chasing.", outcomes: ["Keyword and comment triggers", "Budget and intent qualification", "Calendar links with context"] },
  "workflow-automation": { title: "Orchestration Across the Systems You Actually Use", category: "Automation Platforms", summary: "Connect the five systems that each think they are the source of truth: one event should create the CRM record, notify the team, update the sheet and schedule the follow-up without manual copying.", outcomes: ["Current-state process mapping and platform selection", "Sequencing, conditionals, retries and fallbacks", "Source-of-truth definition plus maintainable documentation"] },
  "make-automation": { title: "Make.com Automation", category: "Automation Platforms", summary: "Visual, maintainable scenarios for the integrations your team depends on every day.", outcomes: ["CRM and app connections", "Branching workflow logic", "Monitoring and documentation"] },
  "n8n-automation": { title: "n8n Automation", category: "Automation Platforms", summary: "Flexible open workflow infrastructure for teams that need control over logic, APIs and data.", outcomes: ["Custom API orchestration", "Reusable workflow nodes", "Self-hosted-ready architecture"] },
  "zapier-automation": { title: "Zapier Automation", category: "Automation Platforms", summary: "Fast, dependable app-to-app connections for the operational tasks that should never be manual.", outcomes: ["Lead and form ingestion", "Notification workflows", "Simple team-owned maintenance"] },
  "vapi": { title: "Vapi Voice Infrastructure", category: "Automation Platforms", summary: "Voice infrastructure for AI agents with structured prompts, tools and CRM actions.", outcomes: ["Tool-enabled voice agents", "Call event handling", "CRM-ready transcripts"] },
  "retell-ai": { title: "Retell AI Voice Infrastructure", category: "Automation Platforms", summary: "Natural voice conversations for qualification, support and appointment workflows.", outcomes: ["Human-like call handling", "Intent and field extraction", "Escalation to your team"] },
  "white-label-ghl": { title: "White-Label GHL", category: "For Agencies", summary: "You sell the strategy. TechPaapi builds and supports the delivery layer under your brand.", outcomes: ["Client-safe fulfilment", "No direct client approach", "Repeatable delivery systems"] },
  "ghl-fulfillment": { title: "GHL Fulfilment", category: "For Agencies", summary: "A technical delivery team for agencies that want to sell GoHighLevel without building every system themselves.", outcomes: ["Implementation capacity", "Documented handover", "Partner-ready communication"] },
  "outsourced-ghl": { title: "Outsourced GHL", category: "For Agencies", summary: "Extend your agency capacity with experienced CRM, automation and funnel operators.", outcomes: ["Flexible delivery support", "Backlog reduction", "Architecture and QA"] },
  "ghl-development-partner": { title: "GHL Development Partner", category: "For Agencies", summary: "Technical depth for complex builds, custom integrations and systems that exceed snapshot templates.", outcomes: ["Custom webhooks and APIs", "Complex workflow design", "Integration troubleshooting"] },
  "managed-ghl-services": { title: "Managed GHL Services", category: "For Agencies", summary: "Keep the system improving after launch with iteration, reporting and operational support.", outcomes: ["Ongoing optimization", "Pipeline leak reporting", "Change management and support"] },
};

function SolutionPage() {
  const { slug } = Route.useParams();
  const solution = solutionData[slug];

  if (!solution) {
    return <main className="flex min-h-screen items-center justify-center bg-background px-6 text-center"><div><h1 className="text-4xl font-bold">Solution not found</h1><Link to="/" className="mt-6 inline-flex text-primary">Back to home</Link></div></main>;
  }

  return (
    <main className="solution-page min-h-screen overflow-x-clip bg-background text-foreground">
      <div className="solution-backdrop" aria-hidden="true" />
      <header className="nav-shell"><div className="site-container flex items-center justify-between py-4"><Link to="/" className="font-display text-xl font-extrabold">Tech<span className="text-[#F5730C]">Paapi</span></Link><nav className="flex items-center gap-5 text-sm text-muted-foreground"><Link to="/portfolio">Portfolio</Link><Link to="/">Home</Link><Button asChild variant="hero" className="hidden sm:inline-flex"><a href="/#pricing">Book Discovery Call <ArrowRight /></a></Button></nav></div></header>
      <section className="relative z-10 mx-auto max-w-6xl px-6 py-24 sm:px-8 lg:py-36"><Link to="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> Back home</Link><div className="mt-10 max-w-4xl"><span className="eyebrow"><Sparkles /> {solution.category}</span><h1 className="mt-7 font-display text-5xl font-extrabold tracking-[-0.07em] sm:text-6xl lg:text-7xl">{solution.title}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-muted-foreground">{solution.summary}</p><Button asChild variant="hero" size="xl" className="mt-9"><a href="/#pricing">Build this system <ArrowRight /></a></Button></div></section>
      <section className="relative z-10 border-y border-border bg-surface/40"><div className="mx-auto grid max-w-6xl gap-4 px-6 py-16 sm:px-8 md:grid-cols-3">{solution.outcomes.map((outcome, index) => <article className="solution-outcome" key={outcome}><span>0{index + 1}</span><CheckCheck className="mt-6 size-5 text-accent" /><h2>{outcome}</h2></article>)}</div></section>
      <section className="relative z-10 mx-auto max-w-6xl px-6 py-24 sm:px-8"><div className="grid gap-6 md:grid-cols-3"><div className="solution-panel md:col-span-2"><Workflow className="size-8 text-primary" /><h2 className="mt-6 font-display text-3xl font-extrabold">One connected system, built around the handoff.</h2><p className="mt-4 max-w-2xl leading-7 text-muted-foreground">We connect the trigger, the conversation, the qualification logic, the calendar and the pipeline so your team sees the right next action without rebuilding context by hand.</p></div><div className="solution-panel"><BarChart3 className="size-8 text-accent" /><p className="mt-6 text-sm uppercase tracking-[0.16em] text-muted-foreground">Operating principle</p><p className="mt-3 text-2xl font-bold">Capture. Qualify. Route. Convert.</p></div></div></section>
    </main>
  );
}
